name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    env:
      CI: true
      PORT: ${{ secrets.PORT }}
      TEST_EMAIL_SENDER: ${{ secrets.TEST_EMAIL_SENDER }}
      TEST_EMAIL_SENDER_PASSWORD: ${{ secrets.TEST_EMAIL_SENDER_PASSWORD }}
      TEST_EMAIL_RECEIVER: ${{ secrets.TEST_EMAIL_RECEIVER }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: yarn install
        run: yarn install
      - name: yarn test
        run: yarn test
